### PR TITLE
Added snapcraft.yaml

### PR DESCRIPTION
**Pull request by seman**
- Added snapcraft.yaml for building snaps
- Added test removal by bundle names from the index pages.

### CODE REVIEW

**Comment by nskaggs** [comment]
Remember the version can be anything you wish. You can even set it to something like 'cwr-blah-edge' to match the channel name if you wish.  I would encourage the idea of setting the snapcraft.yaml file to a source-tag and building that tag. You can then switch the tag around as needed. It's just a pointer to what you want your snap channel to have in it.

**Comment by johnsca** [comment]
I'm +1 to this.

@nskaggs What is the benefit over anchoring the snap to a tag, which would require manual updating, vs master?

**Comment by nskaggs** [comment]
@johnsca Control. If you always want to build a specific branch, set the source-branch. If you only want to build master, then you don't have to set anything, but setting source-branch or source-tag helps make it more explicit. Depending on how often you build the snap and how you plan to publish to channels, these settings may or may not be useful to you.

**Comment by seman** [comment]
@nskaggs It would be nice to have "juju-stable" tag.

**Pull request merged**
